"""

Revision ID: 31576e3fa459
Revises: ef0b846b2490
Create Date: 2024-05-17 14:12:52.619455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31576e3fa459'
down_revision = 'ef0b846b2490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('interviewer_id', sa.BigInteger(), nullable=False), schema='portal')
    op.create_foreign_key(op.f('fk_portal_phase_interviewer_id__user_id'), 'phase', 'user', ['interviewer_id'], ['id'], source_schema='portal', referent_schema='portal')
    op.add_column('vacancy', sa.Column('date_created', sa.DateTime(), nullable=False), schema='portal')
    op.add_column('vacancy', sa.Column('date_closed', sa.DateTime(), nullable=True), schema='portal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'date_closed', schema='portal')
    op.drop_column('vacancy', 'date_created', schema='portal')
    op.drop_constraint(op.f('fk_portal_phase_interviewer_id__user_id'), 'phase', schema='portal', type_='foreignkey')
    op.drop_column('phase', 'interviewer_id', schema='portal')
    # ### end Alembic commands ###
