"""

Revision ID: 8444bf1b90aa
Revises: 745a12258b30
Create Date: 2024-05-20 18:51:13.360046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8444bf1b90aa'
down_revision = '745a12258b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('passed', sa.Boolean(), nullable=True), schema='portal')
    op.add_column('phase', sa.Column('feedback', sa.String(), nullable=True), schema='portal')
    op.sync_enum_values('portal', 'candidatestatus', ['first_communication', 'waiting_tech_stage', 'failed_tech_stage', 'success_tech_stage', 'waiting_final_stage', 'failed_final_stage', 'waiting_offer', 'declined_offer', 'accepted_offer'],
                        [('candidate', 'status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('portal', 'candidatestatus', ['first_communication', 'waiting_tech_stage', 'failed_tech_stage', 'waiting_final_stage', 'failed_final_stage', 'waiting_offer', 'declined_offer', 'accepted_offer'],
                        [('candidate', 'status')],
                        enum_values_to_rename=[])
    op.drop_column('phase', 'feedback', schema='portal')
    op.drop_column('phase', 'passed', schema='portal')
    # ### end Alembic commands ###
