"""

Revision ID: 745a12258b30
Revises: 31576e3fa459
Create Date: 2024-05-20 14:42:14.033656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745a12258b30'
down_revision = '31576e3fa459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phase', 'result_link',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='portal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phase', 'result_link',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='portal')
    # ### end Alembic commands ###
