"""Init migration

Revision ID: ef0b846b2490
Revises: 
Create Date: 2024-05-13 09:18:04.945217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef0b846b2490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('first_communication', 'technical_interview', 'final_interview', name='phasetype', schema='portal').create(op.get_bind())
    sa.Enum('recruiter', 'head_of_department', 'technical_specialist', name='usertype', schema='portal').create(op.get_bind())
    sa.Enum('first_communication', 'waiting_tech_stage', 'failed_tech_stage', 'waiting_final_stage', 'failed_final_stage', 'waiting_offer', 'declined_offer', 'accepted_offer', name='candidatestatus', schema='portal').create(op.get_bind())
    op.create_table('candidate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', postgresql.ENUM('first_communication', 'waiting_tech_stage', 'failed_tech_stage', 'waiting_final_stage', 'failed_final_stage', 'waiting_offer', 'declined_offer', 'accepted_offer', name='candidatestatus', schema='portal', inherit_schema=True, create_type=False), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('telegram', sa.String(), nullable=False),
    sa.Column('resume_link', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_candidate')),
    schema='portal'
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_type', postgresql.ENUM('recruiter', 'head_of_department', 'technical_specialist', name='usertype', schema='portal', inherit_schema=True, create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_user')),
    schema='portal'
    )
    op.create_table('vacancy',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('recruiter_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('specialization_list', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('head_of_department_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['head_of_department_id'], ['portal.user.id'], name=op.f('fk_portal_vacancy_head_of_department_id__user_id')),
    sa.ForeignKeyConstraint(['recruiter_id'], ['portal.user.id'], name=op.f('fk_portal_vacancy_recruiter_id__user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_vacancy')),
    schema='portal'
    )
    op.create_table('phase',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phase_type', postgresql.ENUM('first_communication', 'technical_interview', 'final_interview', name='phasetype', schema='portal', inherit_schema=True, create_type=False), nullable=False),
    sa.Column('vacancy_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('result_link', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['portal.candidate.id'], name=op.f('fk_portal_phase_candidate_id__candidate_id')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['portal.vacancy.id'], name=op.f('fk_portal_phase_vacancy_id__vacancy_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_phase')),
    schema='portal'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase', schema='portal')
    op.drop_table('vacancy', schema='portal')
    op.drop_table('user', schema='portal')
    op.drop_table('candidate', schema='portal')
    sa.Enum('first_communication', 'waiting_tech_stage', 'failed_tech_stage', 'waiting_final_stage', 'failed_final_stage', 'waiting_offer', 'declined_offer', 'accepted_offer', name='candidatestatus', schema='portal').drop(op.get_bind())
    sa.Enum('recruiter', 'head_of_department', 'technical_specialist', name='usertype', schema='portal').drop(op.get_bind())
    sa.Enum('first_communication', 'technical_interview', 'final_interview', name='phasetype', schema='portal').drop(op.get_bind())
    # ### end Alembic commands ###
